name: build adocs and publish to staging

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build html
        id: adocbuild
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"

      - name: Build pdf
        id: adocbuild_pdf
        uses: avattathil/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf -D docs -o files/forvaltningsstandard-begrepsbeskrivelser.pdf -a lang=nb docs/main.adoc"
        continue-on-error: true

      - name: Upload rdf to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.1.0
        id: upload-rdf
        with:
          ontology-type: "specification"
          ontology: "forvaltningsstandard-begrepsbeskrivelser"
          host: "https://staging.fellesdatakatalog.digdir.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY_STAGING }}
          files: |
            docs/index.html text/html nb
            docs/files/forvaltningsstandard-begrepsbeskrivelser.pdf application/pdf nb files/forvaltningsstandard-begrepsbeskrivelser.pdf
            docs/files/StandardForBegrepsbeskrivelse.xsd text/xml nb files/StandardForBegrepsbeskrivelse.xsd
            docs/images/digitaliseringsdirektoratet.png image/png nb images/digitaliseringsdirektoratet.png
            docs/images/UML-v2.0.jpg image/jpeg nb images/UML-v2.0.jpg
            docs/images/UML-v2.0.png image/png nb images/UML-v2.0.png
